### ISSUE TITLE
Robot Animation

### ISSUE THREAD

**Issue by Sahilsk99** [DragonComputer/Dragonfire#125]
I want to build my personal assistant and everything is done but the problem is I am not able to create a animation like Dragonfire  face robot please suggest me to do something animation like Dragonfire

**Comment by mertyildiran** [comment]
@Sahilsk99 we play a gif with [this line](https://github.com/DragonComputer/Dragonfire/blob/3fd3eac5f8b904f8804839b02b3dbcacf1cf2ddd/dragonfire/utilities.py#L63) so you can replace it with your gif.
