### ISSUE TITLE
I can't run dragonfire

### ISSUE THREAD

**Issue by vboasso** [DragonComputer/Dragonfire#14]
**Terminal:**

Successfully installed dragonfire-0.9.2
root@Nb-Vale:/home/vale# dragonfire
Traceback (most recent call last):
  File "/usr/local/bin/dragonfire", line 7, in <module>
    from dragonfire import initiate
  File "/usr/local/lib/python2.7/dist-packages/dragonfire/__init__.py", line 5, in <module>
    from lxml import etree
ImportError: No module named lxml

**Comment by mertyildiran** [comment]
Fixed with https://github.com/DragonComputer/Dragonfire/commit/ef5f3df725b12ec6602a7e007068b1100360fa6c .

@vboasso You can also install lxml package via `sudo apt-get install python-lxml` or `pip install lxml`

**Comment by mertyildiran** [comment]
@vboasso Also please join to our chat room: https://gitter.im/DragonComputer/Lobby
