### ISSUE TITLE
Add Google web search command

### ISSUE THREAD

**Issue by mertyildiran** [DragonComputer/Dragonfire#16]
Add a command like `GOOGLE SEARCH *` or `SEARCH * IN WEB` that will open up a browser window with target URL: https://www.google.com/search?q=[QUERY]

**Comment by ValentinChCloud** [comment]
Hello, the issue is a bit old if it's still relevant I can give a try

**Comment by mertyildiran** [comment]
@ValentinChCloud sure, I would be very happy :blush:

**Comment by mertyildiran** [comment]
Fixed with https://github.com/DragonComputer/Dragonfire/commit/619baadfcea73765ef254cf899d1f2a75c3537f6
