### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by hwpplayer1** [DragonComputer/Dragonfire#35]
Bash integration which lets you us voice , visual , Bash and other shell terminal commands , Cloud integration with closed or open source search engines which lets you directly search something on internet via terminal or GUI and also communication channels such as Skype , Telegram , Hike , IRC etc

This is my first question about this project

Edit :  When i say Cloud integration i mean using Datacenter services

**Comment by mertyildiran** [comment]
This question is completely unclear, incomplete, overly-broad, primarily opinion-based or is not about programming, and it is unlikely to be fixed via editing. Because of these reasons I'm closing this issue.
