### ISSUE TITLE
Zesty install Error.

### ISSUE THREAD

**Issue by rolfoz** [DragonComputer/Dragonfire#36]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"

Error when trying to install downloaded .deb

Selecting previously unselected package libladr4.
(Reading database ... 528671 files and directories currently installed.)
Preparing to unpack .../0-libladr4_0.0.200911a-2.1_amd64.deb ...
Unpacking libladr4 (0.0.200911a-2.1) ...
Selecting previously unselected package libgstreamer1.0-dev.
Preparing to unpack .../1-libgstreamer1.0-dev_1.10.4-1_amd64.deb ...
Adding 'diversion of /usr/bin/dh_gstscancodecs to /usr/bin/dh_gstscancodecs-gst0.10 by libgstreamer1.0-dev'
Adding 'diversion of /usr/share/man/man1/dh_gstscancodecs.1.gz to /usr/share/man/man1/dh_gstscancodecs.1.gz-gst0.10 by libgstreamer1.0-dev'
Unpacking libgstreamer1.0-dev (1.10.4-1) ...
Selecting previously unselected package prover9.
Preparing to unpack .../2-prover9_0.0.200911a-2.1_amd64.deb ...
Unpacking prover9 (0.0.200911a-2.1) ...
Selecting previously unselected package python-nltk.
Preparing to unpack .../3-python-nltk_3.2.1-2_all.deb ...
Unpacking python-nltk (3.2.1-2) ...
Selecting previously unselected package python-pyaudio.
Preparing to unpack .../4-python-pyaudio_0.2.10-1ubuntu1_amd64.deb ...
Unpacking python-pyaudio (0.2.10-1ubuntu1) ...
Selecting previously unselected package flite.
Preparing to unpack .../5-flite_2.0.0-release-3_amd64.deb ...
Unpacking flite (2.0.0-release-3) ...
Selecting previously unselected package python-egenix-mx-base-dev.
Preparing to unpack .../6-python-egenix-mx-base-dev_3.2.9-1_all.deb ...
Unpacking python-egenix-mx-base-dev (3.2.9-1) ...
Selecting previously unselected package python-xlib.
Preparing to unpack .../7-python-xlib_0.14+20091101-5_all.deb ...
Unpacking python-xlib (0.14+20091101-5) ...
Setting up python-egenix-mx-base-dev (3.2.9-1) ...
Processing triggers for install-info (6.3.0.dfsg.1-1) ...
Setting up python-nltk (3.2.1-2) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 added doc-base file...
Registering documents with scrollkeeper...
Setting up flite (2.0.0-release-3) ...
Setting up python-xlib (0.14+20091101-5) ...
Setting up python-pyaudio (0.2.10-1ubuntu1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libladr4 (0.0.200911a-2.1) ...
Setting up libgstreamer1.0-dev (1.10.4-1) ...
Setting up prover9 (0.0.200911a-2.1) ...
Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
Selecting previously unselected package dragonfire.
(Reading database ... 529410 files and directories currently installed.)
Preparing to unpack .../dragonfire_0.9.6_amd64.deb ...
Unpacking dragonfire (0.9.6) ...
Setting up dragonfire (0.9.6) ...
Successfully updated /usr/share/python/dragonfire/bin/python
Cloning into '.'...
remote: Counting objects: 87231, done.
remote: Compressing objects: 100% (10/10), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
dpkg: error processing package dragonfire (--install):
 subprocess installed post-installation script returned error exit status 128
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for man-db (2.7.6.1-2) ...
(Reading database ... 530291 files and directories currently installed.)
Preparing to unpack .../dragonfire_0.9.6_amd64.deb ...
Unpacking dragonfire (0.9.6) over (0.9.6) ...
Setting up dragonfire (0.9.6) ...
Successfully updated /usr/share/python/dragonfire/bin/python
/var/lib/dpkg/info/dragonfire.postinst: 108: cd: can't cd to tools/
dpkg: error processing package dragonfire (--install):
 subprocess installed post-installation script returned error exit status 2
Processing triggers for hicolor-icon-theme (0.15-1) ...
Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for man-db (2.7.6.1-2) ...
(Reading database ... 530289 files and directories currently installed.)
Removing dragonfire (0.9.6) ...
dpkg: warning: while removing dragonfire, directory '/usr/share/python/dragonfire/bin' not empty so not removed
Processing triggers for man-db (2.7.6.1-2) ...
Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Selecting previously unselected package dragonfire.
(Reading database ... 529410 files and directories currently installed.)
Preparing to unpack .../dragonfire_0.9.6_amd64.deb ...
Unpacking dragonfire (0.9.6) ...
Setting up dragonfire (0.9.6) ...
Successfully updated /usr/share/python/dragonfire/bin/python
/var/lib/dpkg/info/dragonfire.postinst: 108: cd: can't cd to tools/
dpkg: error processing package dragonfire (--install):
 subprocess installed post-installation script returned error exit status 2

**Comment by mertyildiran** [comment]
@rolfoz first of all, that's a very unexpected error for me. Thanks for reporting it. :blush: :+1: 

It says, it cannot cd into tools/ so error comes from [this line](https://github.com/DragonComputer/Dragonfire/blob/master/debian/postinst#L20). But before coming to that line it should have executed [this line](https://github.com/DragonComputer/Dragonfire/blob/master/debian/postinst#L17) which means `cd /usr/share/kaldi`.

Is that second time you try to install Dragonfire? What do you have under `/usr/share/kaldi` directory? Could you try to `rm -rf /usr/share/kaldi`? (because Dragonfire put that directory there)

If above solution does not work by itself then please also try to purge Dragonfire `apt-get purge dragonfire`.

If none of the above solutions works then [instal-kaldi.sh](https://github.com/DragonComputer/Dragonfire/blob/master/install-kaldi.sh) is the same script so could you try to run `bash ./install-kaldi.sh`?

**Comment by rolfoz** [comment]
Thanks for the reply.

I tried purging the apt package and then deleting the kaldi directory and
tried again.

I got the same error, so I ran it with dpkg --debug=3771

This time I saw extra info

Cloning into '.'...
remote: Counting objects: 87231, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 87231 (delta 0), reused 6 (delta 0), pack-reused 87220
Receiving objects: 100% (87231/87231), 106.77 MiB | 544.00 KiB/s, done.
Resolving deltas: 100% (67486/67486), done.
extras/check_dependencies.sh: subversion is not installed
extras/check_dependencies.sh: we recommend that you run (our best guess):
 sudo apt-get install  subversion
dpkg: error processing package dragonfire (--install):
 subprocess installed post-installation script returned error exit status 1

So I installed subversion and it installed correctly after that.

Sorry, I should have done more testing before wasting your time.

Thanks again for your work and help!

Rolf

Rolf Schatzmann

Mobile: 0428 400024

**Comment by mertyildiran** [comment]
@rolfoz no, I actually realized my mistake:

I think you interrupted the installation while it's cloning Kaldi into `/usr/share/kaldi` which is an event that I haven't considered in the past. So we should change [this part](https://github.com/DragonComputer/Dragonfire/blob/master/debian/postinst#L12-L18) as:

```
if [ -d "$KALDI_DIRECTORY" ]; then
  rm -rf $KALDI_DIRECTORY
fi
mkdir $KALDI_DIRECTORY
cd $KALDI_DIRECTORY
git clone https://github.com/kaldi-asr/kaldi.git .
```

and also we should add a file named `postrm` into `Dragonfire/debian/` directory with this content:

```
KALDI_DIRECTORY=/usr/share/kaldi
rm -rf $KALDI_DIRECTORY
```

so it will be able remove Kaldi when you run `apt-get remove dragonfire` or `apt-get purge dragonfire`.

After these changes we should check the validity by [building the package](https://github.com/DragonComputer/Dragonfire/blob/master/CONTRIBUTING.md#build-the-debian-package) and installing the new package. (a package named `dragonfire_0.9.6_amd64.deb` will be created in the upper directory `../`)

Could you do that for me and send a pull request?

**Comment by mertyildiran** [comment]
@rolfoz I'm waiting for your pull request. Are you planning to send a pull request anytime soon with the fix I mentioned in my the previous comment? If your answer is no then I will make the changes by myself. But because you are the reporter of this issue, I think you deserve to commit the changes more than me.

**Comment by rolfoz** [comment]
I'm sorry but I am not able to make a pull request. Please can you do it.
Thanks.

On 19 Oct. 2017 9:57 pm, "Mehmet Mert Yıldıran" <notifications@github.com>
wrote:

@rolfoz <https://github.com/rolfoz> I'm waiting for your pull request. Are
you planning to send a pull request anytime soon with the fix I mentioned
in my the previous comment? If your answer is no then I will make the
changes by myself. But because you are the reporter of this issue, I think
you deserve to commit the changes more than me.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DragonComputer/Dragonfire/issues/36#issuecomment-337915981>,
or mute the thread

**Comment by mertyildiran** [comment]
Fixed with https://github.com/DragonComputer/Dragonfire/commit/8019008202b003c7e65318c8b5bea79539b851fd
