### ISSUE TITLE
another zesty install issue

### ISSUE THREAD

**Issue by nergdron** [DragonComputer/Dragonfire#37]
This is on ubuntu 17.04/amd64. The package doesn't depend on subversion or libatlas-base-dev, but it fails to compile if either of those are missing. Should be an easy fix to the package dependencies list.

**Comment by mertyildiran** [comment]
@nergdron thanks for reporting it :+1: 

Could you please add those packages to the end of [this line](https://github.com/DragonComputer/Dragonfire/blob/master/debian/control#L11) and send a pull request? :blush:

**Comment by nergdron** [comment]
https://github.com/DragonComputer/Dragonfire/pull/38
