### ISSUE TITLE
Dragonfire is not able to recognise my voice inputs

### ISSUE THREAD

**Issue by fabianTMC** [DragonComputer/Dragonfire#46]
This is what I see in the terminal 

```bash
$ dragonfire 
_______________________________________________________________

Dragonfire: GOOD AFTERNOON SIR
_______________________________________________________________

Traceback (most recent call last):
  File "/usr/share/python/dragonfire/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==0.9.6', 'console_scripts', 'dragonfire')()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/__init__.py", line 486, in initiate
    start(args)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/__init__.py", line 56, in start
    recognizer = KaldiRecognizer()
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/sr/kaldi.py", line 37, in __init__
    self.decoder_pipeline = DecoderPipeline({"decoder" : decoder_conf})
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/sr/decoder.py", line 20, in __init__
    self.create_pipeline(conf)
  File "/usr/share/python/dragonfire/local/lib/python2.7/site-packages/dragonfire/sr/decoder.py", line 50, in create_pipeline
    self.asr.set_property(key, val)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by mertyildiran** [comment]
@fabianTMC if you have installed Dragonfire via `.deb` package then it should have [set](https://github.com/DragonComputer/Dragonfire/blob/2dc23a303af76aec8194b064ae1d725d3c6bae0b/debian/fire/dragonfire#L3) an environment variable called `GST_PLUGIN_PATH` every time it started. Though it seems not the case...

So you should set this environment variable before starting Dragonfire with this command:

```
export GST_PLUGIN_PATH=/usr/share/kaldi/src/gst-plugin
```

**Comment by fabianTMC** [comment]
Yes, I installed it via the `.deb` package. `GST_PLUGIN_PATH` was not set but even after setting it and running Dragonfire, the issue persists.

**Comment by mertyildiran** [comment]
@fabianTMC Is Kaldi available (compiled) under `/usr/share/kaldi` directory?

As the last resort; please try to run [this shell script](https://github.com/DragonComputer/Dragonfire/blob/master/install.sh).

**Comment by fabianTMC** [comment]
I had already run that script. Turns out Kaldi hadn't been compiled. Traced it down to a missing subversion dependency which had caused an issue with the dpkg post install configuration for dragonfire. Fixed that and compiled Kaldi manually and everything works as expected now.

**Comment by mertyildiran** [comment]
@fabianTMC yeah it is fixed with https://github.com/DragonComputer/Dragonfire/commit/22690829e62e935425bf769c15937b1c951a685b (in next release)

I'm glad to hear that it's worked. :+1: :blush:
