### ISSUE TITLE
depend on automake, autoconf and libtool

### ISSUE THREAD

**Issue by jklmnn** [DragonComputer/Dragonfire#52]
The package doesn't depend on automake, autoconf and libtool so the install will fail on a fresh system.

**Comment by mertyildiran** [comment]
@jklmnn hmm, OK. Could you please add those packages to the end of these lines and send a pull request? :blush: 

https://github.com/DragonComputer/Dragonfire/blob/master/debian/control#L11
https://github.com/DragonComputer/Dragonfire/blob/master/install-dev.sh#L4
https://github.com/DragonComputer/Dragonfire/blob/master/install.sh#L4

**Comment by jklmnn** [comment]
@mertyildiran done, see #53
