### ISSUE TITLE
Could we run autopep8 over the entire codebase?

### ISSUE THREAD

**Issue by cclauss** [DragonComputer/Dragonfire#59]
There are [lots of issues](https://travis-ci.org/DragonComputer/Dragonfire/jobs/307696317#L2825-L2852) with mixed indentation (tab and space indentation on the same line) and other formatting issues.  Is there a need to keep using tab indentation?  Other language communities (esp. golang) are demonstrating that programer performance increases when code formatting is done automatically and with no options/special cases turned on.  Different standards for code formatting on different projects reduces both readability and portability.

Would it be of interest to have a PR that [autopep8](https://pypi.python.org/pypi/autopep8/)s all Python code in the repo?  [yapf](https://pypi.python.org/pypi/yapf) would be an alternative approach.

**Comment by mertyildiran** [comment]
I'm weak on coding conventions. @cclauss it's up to you. Please, you decide these kind of matters. I will accept your PRs.
