### ISSUE TITLE
AttributeError: TTA instance has no attribute 'define_and_execute'

### ISSUE THREAD

**Issue by ianni67** [DragonComputer/Dragonfire#60]
HI, this software is a great job but I'm getting an error every time I run it:
`ianni@goliath:~$ dragonfire 
_______________________________________________________________

Traceback (most recent call last):
  File "/usr/local/bin/dragonfire", line 9, in <module>
    load_entry_point('dragonfire==0.9.7', 'console_scripts', 'dragonfire')()
  File "/usr/local/lib/python2.7/dist-packages/dragonfire/__init__.py", line 517, in initiate
    dragon_greet()
  File "/usr/local/lib/python2.7/dist-packages/dragonfire/__init__.py", line 477, in dragon_greet
    userin.define_and_execute(["echo"], "To activate say 'Dragonfire!' or 'Wake Up!'")
AttributeError: TTA instance has no attribute 'define_and_execute'`

I installed the github version of dragonfire, downloaded a few minutes ago.
Did not get such error with the .deb package, however, it did not receive voice commands and, therefore, I uninstalled it and installed from scratch using the install.sh script in the git cloned folder.
Any help, please?

**Comment by mertyildiran** [comment]
@ianni67 current state of this repository is unstable. Please jump to: https://github.com/DragonComputer/Dragonfire/tree/6cf5431b43073768288ba5c4fb9be83ef08f6cfb

**Comment by ianni67** [comment]
thank you

**Comment by mertyildiran** [comment]
@ianni67 fixed with https://github.com/DragonComputer/Dragonfire/commit/4a78bfd6d889b09f95292ef550f708d6e1863170
