### ISSUE TITLE
ubuntu 17.10 kurulum sorunu

### ISSUE THREAD

**Issue by obafemi** [DragonComputer/Dragonfire#65]
Kurulum yapmak için install.sh dosyasını çalıştırdığım zaman bilgisayarım kitleniyor. .deb dosyasını kurduğum zamanda program çalışmıyor.

**Comment by mertyildiran** [comment]
@obafemi you should have used English language only to explain your problem. This is why I'm closing this issue. Please file a new issue and explain your problem in English.
