### ISSUE TITLE
Dragonfire takes more than 30 min to install

### ISSUE THREAD

**Issue by Vipult** [DragonComputer/Dragonfire#68]
Hi..I tried to install Latest hotfix of Dragonfire on Ubuntu 17.10...the installation keeps going and
does not seem to finish even after 2 hours...May I know whether I am doing anything wrong?I am following the instructions given

**Comment by hosford42** [comment]
I had a similar issue. It would seem the install is extremely memory-intensive, resulting in a lot of paging which can cause very long runtimes.

**Comment by mertyildiran** [comment]
@Vipult and @hosford42 Dragonfire compiles Kaldi ASR on installation time. This is why it takes so much time and consumes that amount of memory.
