### ISSUE TITLE
Memory corruption when running Dragonfire

### ISSUE THREAD

**Issue by lalchand-pandia** [DragonComputer/Dragonfire#72]
Hi,

Please note I am using tensorflow CPU version and deepspeech CPU version.
When I run dragonfire, it greets me with GOOD AFTERNOON.
The output of htop indicates I have enough memory. At the time of error, RAM memory used is 10GB out of 23 GB.
Then I get following error:
_______________________________________________________________

Dragonfire: GOOD AFTERNOON SIR
_______________________________________________________________

*** Error in `/usr/bin/python3': malloc(): memory corruption (fast): 0x000000000e89ba70 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fd0127c17e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7fd0127cc651]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fd0127ce184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7fd002cb1e78]
/home/lalchand/.local/lib/python3.5/site-packages/deepspeech/lib/libtensorflow_framework.so(_ZN10tensorflow24TfCheckOpHelperOutOfLineERKNS_6StatusEPKc+0x8d)[0x7fcf9d68c4ed]
/home/lalchand/.local/lib/python3.5/site-packages/deepspeech/lib/libtensorflow_framework.so(+0x3750a9)[0x7fcf9d5180a9]
/lib64/ld-linux-x86-64.so.2(+0x106ba)[0x7fd012d416ba]
/lib64/ld-linux-x86-64.so.2(+0x107cb)[0x7fd012d417cb]
/lib64/ld-linux-x86-64.so.2(+0x158e2)[0x7fd012d468e2]
/lib64/ld-linux-x86-64.so.2(+0x10564)[0x7fd012d41564]
/lib64/ld-linux-x86-64.so.2(+0x14da9)[0x7fd012d45da9]
/lib/x86_64-linux-gnu/libdl.so.2(+0xf09)[0x7fd012546f09]
/lib64/ld-linux-x86-64.so.2(+0x10564)[0x7fd012d41564]
/lib/x86_64-linux-gnu/libdl.so.2(+0x1571)[0x7fd012547571]
/lib/x86_64-linux-gnu/libdl.so.2(dlopen+0x31)[0x7fd012546fa1]
/usr/bin/python3(_PyImport_FindSharedFuncptr+0x8a)[0x60b35a]
/usr/bin/python3(_PyImport_LoadDynamicModuleWithSpec+0x12b)[0x61000b]
/usr/bin/python3[0x610538]
/usr/bin/python3(PyCFunction_Call+0x106)[0x4e9c36]

**Comment by mertyildiran** [comment]
@lalchand-pandia fix with https://github.com/DragonComputer/Dragonfire/commit/43f21fecff8fce265c01b50df472675cd729f953 

Please download and install new [dragonfire_0.9.9_amd64.deb](https://github.com/DragonComputer/Dragonfire/releases/download/v0.9.9/dragonfire_0.9.9_amd64.deb)
