### ISSUE TITLE
Not working on Debian 9

### ISSUE THREAD

**Issue by turtle-bazon** [DragonComputer/Dragonfire#76]
I've downloaded deb package and install it. First, it doesn't install. After installing python3-wheel installation seems successful, but it not starts:

`/usr/bin/dragonfire: 3: /usr/bin/dragonfire: /usr/share/python/dragonfire/bin/dragonfire: not found`

Actually, there are no file `/usr/share/python/dragonfire/bin/dragonfire`

**Comment by mamantoha** [comment]
The same on Kubuntu 18.04.

```
whereis dragonfire 
dragonfire: /usr/bin/dragonfire /usr/share/dragonfire /usr/share/man/man1/dragonfire.1.gz
```

```
cat /usr/bin/dragonfire
#!/bin/sh

/usr/share/python/dragonfire/bin/dragonfire $@
```

```
file /usr/share/python/dragonfire/bin/dragonfire
/usr/share/python/dragonfire/bin/dragonfire: cannot open `/usr/share/python/dragonfire/bin/dragonfire' (No such file or directory)
```

**Comment by turtle-bazon** [comment]
I can investigate but have not experience in python. :) So I don't know how to help. What is this file `/usr/share/python/dragonfire/bin/dragonfire`? It not present in dpkg package. So, is it should be generated during post-install scripts? Give me direction. :)

**Comment by turtle-bazon** [comment]
I've looked at post-inst scripts and didn't see any generation of dragonfire binary at that path. So I'm confused now.

**Comment by mertyildiran** [comment]
@mamantoha @turtle-bazon is it under `/usr/share/python3/dragonfire/bin/dragonfire` ? if so we forgot to change [this line](https://github.com/DragonComputer/Dragonfire/blob/master/debian/fire/dragonfire#L3). 😕

If that's the case then please fix it and send a pull request.

**Comment by vladislavyuzbekov** [comment]
dragonfire -h
/usr/bin/dragonfire: 3: /usr/bin/dragonfire: /usr/share/python/dragonfire/bin/dragonfire: not found

**Comment by vladislavyuzbekov** [comment]
vladislav@vladislav-P5QL-PRO:~$ dragonfire -h
/usr/bin/dragonfire: 3: /usr/bin/dragonfire: /usr/share/python/dragonfire/bin/dragonfire: not found

**Comment by turtle-bazon** [comment]
No dragonfire dir neither in `/usr/share/python` nor in `/usr/share/python3`

**Comment by mertyildiran** [comment]
@turtle-bazon @mamantoha @vladislavyuzbekov I fixed this issue with https://github.com/DragonComputer/Dragonfire/commit/d2ca3fb101c88c8244fa949ab2428282843f9146 and updated the release. So please redownload [dragonfire_1.0.0_amd64.deb](https://github.com/DragonComputer/Dragonfire/releases/download/v1.0.0/dragonfire_1.0.0_amd64.deb) file and install it again.

We apologize for the inconvenience. 😊 Please report it if you face with an issue again.

**Comment by turtle-bazon** [comment]
New dragonfire sucessfully installed, but can't be run:
```
turtle@working-turtle /tmp $ dragonfire
Traceback (most recent call last):                                    
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 63, in __load
    try: root = nltk.data.find('corpora/%s' % zip_name)
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource 'corpora/brown.zip/brown/' not found.  Please use the
  NLTK Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/turtle/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dragonfire", line 11, in <module>
    load_entry_point('dragonfire==1.0.0', 'console_scripts', 'dragonfire')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/dragonfire/__init__.py", line 40, in <module>
    from dragonfire.nlplib import Classifier, Helper
  File "/usr/lib/python3/dist-packages/dragonfire/nlplib.py", line 31, in <module>
    brown_train = brown.tagged_sents(categories='news')
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 99, in __getattr__
    self.__load()
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 64, in __load
    except LookupError: raise e
  File "/usr/lib/python3/dist-packages/nltk/corpus/util.py", line 61, in __load
    root = nltk.data.find('corpora/%s' % self.__name)
  File "/usr/lib/python3/dist-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource 'corpora/brown' not found.  Please use the NLTK
  Downloader to obtain the resource:  >>> nltk.download()
  Searched in:
    - '/home/turtle/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

```

**Comment by turtle-bazon** [comment]
It seems that `printf "import nltk\nnltk.download('names')\nnltk.download('brown')\nnltk.download('wordnet')\nnltk.download('punkt')" | python3` downloaded resources to root's home directory.

**Comment by turtle-bazon** [comment]
After executing this line as user it launches, but I think that is not correct behavior.
