### ISSUE TITLE
Attempting to install, but the available python3 package in Ubuntu is too new?

### ISSUE THREAD

**Issue by 08server** [DragonComputer/Dragonfire#85]
`dragonfire : Depends: python3 (< 3.6) but 3.6.5-3ubuntu1 is installed`

**Comment by mertyildiran** [comment]
@08server I think the only constraint we have is in [here](https://github.com/DragonComputer/Dragonfire/blob/master/debian/control#L10) so is that the whole traceback or error output? Could you share more information?

**Comment by 08server** [comment]
`$ sudo dpkg -i dragonfire_1.0.0_amd64.deb
Selecting previously unselected package dragonfire.
(Reading database ... 396265 files and directories currently installed.)
Preparing to unpack dragonfire_1.0.0_amd64.deb ...
Unpacking dragonfire (1.0.0) ...
dpkg: dependency problems prevent configuration of dragonfire:
 dragonfire depends on python3 (<< 3.6); however:
  Version of python3 on system is 3.6.5-3ubuntu1.

dpkg: error processing package dragonfire (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.3-2) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-11ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 dragonfire
`

**Comment by 08server** [comment]
@mertyildiran 
```
$ sudo dpkg -i dragonfire_1.0.0_amd64.deb
Selecting previously unselected package dragonfire.
(Reading database ... 396265 files and directories currently installed.)
Preparing to unpack dragonfire_1.0.0_amd64.deb ...
Unpacking dragonfire (1.0.0) ...
dpkg: dependency problems prevent configuration of dragonfire:
 dragonfire depends on python3 (<< 3.6); however:
  Version of python3 on system is 3.6.5-3ubuntu1.

dpkg: error processing package dragonfire (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for man-db (2.8.3-2) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-11ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 dragonfire
```

**Comment by mertyildiran** [comment]
@08server probably because I packed `.deb` file with Python 3.6 machine. Please try to install Dragonfire with `sudo ./install.sh` (alternative installation method)

**Comment by 08server** [comment]
@mertyildiran Yeah, installed fine with that method... thanks
