### ISSUE TITLE
Is Dragonfire going to save my personal data?

### ISSUE THREAD

**Issue by SamsadSajid** [DragonComputer/Dragonfire#86]
Is Dragonfire going to save my personal data? For example, is it going to keep what I view, search, say, type or what my folders contain?

**Comment by mertyildiran** [comment]
@SamsadSajid no, Dragonfire does not save your personal data. Only if you use the learning ability, it stores the facts to a database.

By the way GitHub issues section is not a question answering platform or a forum like thing. So please use [our Gitter chat room](https://gitter.im/DragonComputer/Lobby) to ask such questions.
