### ISSUE TITLE
Crash: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Ag0s** [DragonComputer/Dragonfire#88]
For a yet unknown reason Dragonfire crashes after telling me "Good morning sir".

Currently I am unable to investigate the issue as I have not yet found the dumped core. Do you have any idea where I can locate it? Its not on the OS core dump location like /var/crash/.

Running kernel:
Ubuntu 4.4.0-134-generic

**Comment by Ag0s** [comment]
It seems an issue with deepspeech. syslog tells me the following:

Aug 30 10:21:30 PC kernel: [10547.898010] traps: dragonfire[24116] trap invalid opcode ip:7fb8ca5935a7 sp:7ffdc25b5960 error:0 in libdeepspeech.so[7fb8ca18c000+1dfa000]
Aug 30 10:55:00 PC kernel: [12558.031660] traps: dragonfire[3727] trap invalid opcode ip:7fce651e65a7 sp:7ffeff7943b0 error:0 in libdeepspeech.so[7fce64ddf000+1dfa000]

Any ideas?

**Comment by mertyildiran** [comment]
@Ag0s based on `libdeepspeech.so` I guess it's related to Mozilla's DeepSpeech so you should seek for the answer in https://github.com/mozilla/DeepSpeech
