### ISSUE TITLE
‘async’ is a reserved word in Python >= 3.7

### ISSUE THREAD

**Issue by cclauss** [DragonComputer/Dragonfire#96]
https://github.com/DragonComputer/Dragonfire/blob/master/dragonfire/__init__.py#L115 is a Syntax Error in Python >= 3.7.

This was [fixed in upstream](https://github.com/tweepy/tweepy/pull/1042) by moving from ___async___ to ___is_async___.

**Comment by cclauss** [comment]
Bump on this one...

**Comment by mertyildiran** [comment]
@cclauss fixed with 49f5ca6eae2ec9be80d3e077182207298522ceb6
